In [ ]:
from cj.models import BayesianCJ, BTMCJ, BayesianCJMC
import cj

In [ ]:
BCJ = BayesianCJ()
BTM = BTMCJ()
BCJMC = BayesianCJMC()

In [ ]:
BCJ.check()

In [ ]:
BTM.check()

In [ ]:
BTM = BTMCJ(5)

In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("ent n_items=5 res 0 k=5 new.csv")

# Extract the values from the DataFrame
values = df.values

# Get the shape of the DataFrame
df_shape = df.shape

values, df_shape

In [ ]:
BTM.run(values)

In [ ]:
# Optimised version: 
BTM.get_ranking()

In [ ]:
BTM.get_ranking()

In [ ]:
import numpy as np

class BradleyTerryModel:
    def __init__(self):
        self.weights = None
    
    def fit(self, X, y, max_iter=100, tol=1e-4):
        n_samples, n_features = X.shape
        self.weights = np.ones(n_features)
        
        for _ in range(max_iter):
            prev_weights = np.copy(self.weights)
            
            for i in range(n_features):
                wins = 0
                losses = 0
                
                for j in range(n_samples):
                    if X[j, i] == 1:
                        wins += 1
                    elif X[j, i] == -1:
                        losses += 1
                
                self.weights[i] = np.log(wins / losses)
            
            if np.linalg.norm(self.weights - prev_weights) < tol:
                break
    
    def predict(self, X):
        probabilities = np.exp(X @ self.weights)
        return probabilities / np.sum(probabilities)

In [ ]:
# Import the necessary modules
import numpy as np

class BradleyTerryModel:
    def __init__(self):
        self.weights = None
    
    def fit(self, X, y, max_iter=100, tol=1e-4):
        n_samples, n_features = X.shape
        self.weights = np.ones(n_features)
        
        for _ in range(max_iter):
            prev_weights = np.copy(self.weights)
            
            for i in range(n_features):
                wins = 0
                losses = 0
                
                for j in range(n_samples):
                    if X[j, i] == 1:
                        wins += 1
                    elif X[j, i] == -1:
                        losses += 1
                
                self.weights[i] = np.log(wins / losses)
            
            if np.linalg.norm(self.weights - prev_weights) < tol:
                break
    
    def predict(self, X):
        probabilities = np.exp(X @ self.weights)
        return probabilities / np.sum(probabilities)

# Example usage
X = np.array([[1, 0, 1], [0, 1, 0], [1, 1, 0], [0, 1, 1]])
y = np.array([1, -1, 1, -1])

model = BradleyTerryModel()
model.fit(X, y)

test_data = np.array([[1, 0, 0], [0, 1, 1]])
predictions = model.predict(test_data)

print(predictions)
# from cj.models import BTMCJ

# Create an instance of the BTMCJ class
# btm = BTMCJ()

# # Use the methods and attributes of the BTMCJ instance
# btm.check()
# btm.run(values)
# ranking = btm.get_ranking()

In [ ]:
data = [
    [0, 1, 0],
    [0, 1, 0],
    [0, 1, 1],
    [0, 1, 1],
    [0, 1, 1],
    [0, 3, 0],
    [0, 3, 3],
    [0, 3, 3],
    [0, 3, 3],
    [0, 3, 3],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [2, 1, 2],
    [2, 1, 2],
    [2, 1, 2],
    [2, 3, 2],
    [3, 2, 3],
    [3, 2, 3],
    [3, 2, 3],
]

In [ ]:
from cj.models import BTMCJ
import numpy as np

In [ ]:
data = np.asarray([
    [0, 1, 0],
    [0, 1, 0],
    [0, 3, 0],
    [1, 0, 1],
    [1, 0, 1],
    [1, 0, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [2, 1, 2],
    [2, 1, 2],
    [2, 1, 2],
    [2, 3, 2],
    [3, 0, 3],
    [3, 0, 3],
    [3, 0, 3],
    [3, 0, 3],
    [3, 2, 3],
    [3, 2, 3],
    [3, 2, 3],
])

In [ ]:
BTM_check = BTMCJ(4)

In [ ]:
BTM_check.run(data)

In [ ]:
data.shape

In [ ]:
BTM_check.final_rank

In [ ]:
BTM_check.get_ranking()

In [ ]:
BTM_check.run(data)

In [ ]:
BTM_check.get_ranking()

In [ ]:
BTM_check.p

In [ ]:
BTM_check.p_prime

In [ ]:
import numpy as np

# Number of entities (assuming they are labeled 0, 1, 2, 3)
num_entities = 4

# Initialize latent strengths (randomly or with some initial guess)
theta = np.zeros(num_entities)

# Maximum likelihood estimation
def log_likelihood(theta):
    log_like = 0
    for row in data:
        i, j, outcome = row
        p_ij = np.exp(theta[i]) / (np.exp(theta[i]) + np.exp(theta[j]))
        log_like += outcome * np.log(p_ij) + (1 - outcome) * np.log(1 - p_ij)
    return log_like

# Optimize using gradient descent (you can use other optimizers)
learning_rate = 0.01
for _ in range(10):  # Adjust the number of iterations
    gradient = np.zeros(num_entities)
    for row in data:
        i, j, outcome = row
        p_ij = np.exp(theta[i]) / (np.exp(theta[i]) + np.exp(theta[j]))
        gradient[i] += outcome - p_ij
        gradient[j] += (1 - outcome) - (1 - p_ij)
    theta += learning_rate * gradient

# Rank entities based on estimated strengths
ranked_entities = np.argsort(-theta)  # Descending order

print("Estimated strengths (theta):", theta)
print("Ranked entities:", ranked_entities)


In [ ]:
from cj.models import BTMCJ
import numpy as np

In [ ]:
import pandas as pd

# Read the CSV file into a DataFrame
df = pd.read_csv("ent n_items=5 res 5 k=30.csv")

# Extract the values from the DataFrame
values = df.values

# Get the shape of the DataFrame
df_shape = df.shape

values, df_shape

values

In [ ]:
BTM_realdata = BTMCJ(5)
# BTM_realdata.run(values) 

In [ ]:
BTM_realdata.get_ranking()

In [ ]:
BTM_realdata.p

In [ ]:
BTM_realdata.final_rank

In [ ]:
target = [4,5,9,0,3,1,8,7,6,2]

In [ ]:
def normalised_kendall_tau_distance(values1, values2):
    """
        Compute the Kendall tau distance.
    """
    n = len(values1)
    assert len(values2) == n, "Both lists have to be of equal length"
    i, j = np.meshgrid(np.arange(n), np.arange(n))
    a = np.argsort(values1)
    b = np.argsort(values2)
    ndisordered = np.logical_or(np.logical_and(a[i] < a[j], b[i] > b[j]), np.logical_and(a[i] > a[j], b[i] < b[j])).sum()
    return ndisordered / (n * (n - 1))

In [ ]:
normalised_kendall_tau_distance(BTM_realdata.final_rank, target)

In [ ]:
import numpy as np

class BradleyTerryModel:
    def __init__(self):
        self.weights = None
    
    def fit(self, X, y, max_iter=100, tol=1e-4):
        n_samples, n_features = X.shape
        self.weights = np.ones(n_features)
        
        for _ in range(max_iter):
            prev_weights = np.copy(self.weights)
            
            for i in range(n_features):
                wins = 0
                losses = 0
                
                for j in range(n_samples):
                    if X[j, i] == 1:
                        wins += 1
                    elif X[j, i] == -1:
                        losses += 1
                
                self.weights[i] = np.log(wins / losses)
            
            if np.linalg.norm(self.weights - prev_weights) < tol:
                break
    
    def predict(self, X):
        probabilities = np.exp(X @ self.weights)
        return probabilities / np.sum(probabilities)

In [2]:
import numpy as np
from cj.models import BayesianCJ, BTMCJ

In [3]:
BCJ = BayesianCJ(4)
BTM = BTMCJ(4)

In [4]:
data = np.asarray([
    [0, 1, 0],
    [0, 1, 0],
    [0, 3, 0],
    [1, 0, 1],
    [1, 0, 1],
    [1, 0, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [1, 2, 1],
    [2, 1, 2],
    [2, 1, 2],
    [2, 1, 2],
    [2, 3, 2],
    [3, 0, 3],
    [3, 0, 3],
    [3, 0, 3],
    [3, 0, 3],
    [3, 2, 3],
    [3, 2, 3],
    [3, 2, 3],
])

In [5]:
BCJ.run(data)
BTM.run(data)

2024-06-06 12:47:44,466	INFO worker.py:1553 -- Started a local Ray instance.


In [5]:
BCJ.res

array([3, 1, 0, 2])

In [7]:
BCJ.rank_scores

[3.046875, 2.09765625, 3.05859375, 1.796875]

In [7]:
BCJ.prob_dist

{0: [0.018798828125, 0.207763671875, 0.481201171875, 0.292236328125],
 1: [0.24481201171875, 0.45635986328125, 0.25518798828125, 0.04364013671875],
 2: [0.0238037109375, 0.1968994140625, 0.4761962890625, 0.3031005859375],
 3: [0.36181640625, 0.48974609375, 0.13818359375, 0.01025390625]}

In [8]:
BTM.optimal_params

array([-0.44654627,  0.04240265, -0.41580243,  0.81994508])

In [9]:
BTM.rank

array([3, 1, 2, 0])

In [ ]:
BCJ.rank_scores

[3.046875, 2.09765625, 3.05859375, 1.796875]